In [ ]:
#NumPy
import numpy

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
x = np.linspace(0,10,100)
y = np.sin(x)
plt.plot(x,y,label ='sin(x)')
plt.title("Sin Wave")
plt.xlabel('x')
plt.ylabel('sin(x)')
plt.legend()
plt.show()


In [17]:
import numpy as np
#np.array(object, dtype=None. int float)
lis = [1,2,3]
print(lis, type(lis))
arr = np.array(lis)
print(arr, type(arr))

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


In [ ]:
#Arange - create evenly space values within a range
#np.arrange(start, stop, step) ---- stop is excluded
arr = np.arange(0,10,0.5)
print(arr)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]


In [21]:
#linspace ---- crt a array with evenly spaced no over a specified interval
#np.linspace(start, stop, num)
arr = np.linspace(0,1,5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [22]:
#empty---- creates uninitialies array of specified space
#np.empty(shape, dtype = float)
arr = np.empty((2,3))
print(arr)

[[0.81652778 0.53277778 0.81652778]
 [4.22877778 5.77652778 0.53277778]]


In [29]:
#eye method ---- used to generate 2D idendity matrix
#np.eye(N, M= None, k=0, dtype = float)
arr = np.eye(3)
print(arr)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [35]:
#ones/zeros method --- creates an array filled with one
#np.ones(shape, dtype = float)
arr = np.ones((2,3))
print(arr)
arr = np.zeros((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [32]:
#full ---- initialise array with custom number
#np.full(shape, fill value, dtype = None)
arr = np.full((2,3),5)
print(arr)

[[5 5 5]
 [5 5 5]]


In [ ]:
#copy--- creates deep copy of an array
#np.copy(a)

In [46]:
#fromfunction ---- creates an array by applying a func to each coordinate
#np.fromfunction(function, shape, dtype = float)
arr = np.fromfunction(lambda i, j: (i+1)*(j+1)  , (11,11))
print(arr)

[[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.]
 [  2.   4.   6.   8.  10.  12.  14.  16.  18.  20.  22.]
 [  3.   6.   9.  12.  15.  18.  21.  24.  27.  30.  33.]
 [  4.   8.  12.  16.  20.  24.  28.  32.  36.  40.  44.]
 [  5.  10.  15.  20.  25.  30.  35.  40.  45.  50.  55.]
 [  6.  12.  18.  24.  30.  36.  42.  48.  54.  60.  66.]
 [  7.  14.  21.  28.  35.  42.  49.  56.  63.  70.  77.]
 [  8.  16.  24.  32.  40.  48.  56.  64.  72.  80.  88.]
 [  9.  18.  27.  36.  45.  54.  63.  72.  81.  90.  99.]
 [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100. 110.]
 [ 11.  22.  33.  44.  55.  66.  77.  88.  99. 110. 121.]]


In [44]:
rows = np.arange(1,11).reshape(-1,1)
cols = np.arange(1,11)
table = rows*cols
print(table)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]
